[env]
REMOTE_DATABASE_URL = "postgresql://neondb_owner:npg_j2rspKAfQu1E@ep-delicate-sunset-aa62a264-pooler.westus3.azure.neon.tech/neondb?sslmode=require&channel_binding=require"
DATABASE_URL="sqlite:template.db"
